output_dir = "output/ackley"
seed = 0
function = "ackley"
log_level = "DEBUG"          # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

method = "partial-ucb"

num_initial_samples = 5

num_iter = 20

[function_config]
ndim = 2

[method_config]
alpha = 1.0
