output_dir = "output/ackley_full_logei"
seed = 0
function = "ackley"
log_level = "DEBUG"                     # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

method = "full-logei"

num_initial_samples = 5

num_iter = 20

[function_config]
ndim = 2

[method_config]
