output_dir = "output/ackley"
seed = 0
function = "ackley"
log_level = "DEBUG"          # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

method = "partial-ucb"

num_initial_samples = 5

max_iter = 20

[function_config]
ndim = 2
cost1 = 1
cost2 = 1

[method_config]
alpha = 1.0
